server:
  port: 8765
spring:
  application:
    name: api-gateway


#  cloud:
#    gateway:
#      default-filters:
#        - RemoveRequestHeader=Cookie
#      routes:
#        - id: book-service
#          uri: lb://BOOK-SERVICE
#          predicates:
#            - Path=/api/book/**
#
#        - id: exchange-service
#          uri: lb://EXCHANGE-SERVICE
#          predicates:
#            - Path=/api/exchange/**


#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
